<a href="https://colab.research.google.com/github/prog815/DLSchool-deep_learning_2019-20/blob/master/%5Bhomework%2C_prodv%5D3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Домашнее задание 2. Библиотека Numpy и линейная алгебра.
</b></h2>

---

In [0]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [0]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
print(a.ndim, a.shape)
# ========
print(a)
print(b)

2 (100, 100)
[[0.2071373  0.90689139 0.20107264 ... 0.97516725 0.55605555 0.85444148]
 [0.73293532 0.8610566  0.34495355 ... 0.51983802 0.21256691 0.45942269]
 [0.53264116 0.77637886 0.85510495 ... 0.958841   0.50636069 0.10027906]
 ...
 [0.47850803 0.29169787 0.57722969 ... 0.99841313 0.67159684 0.4301041 ]
 [0.04130979 0.86170942 0.82867115 ... 0.9181689  0.35207683 0.70059198]
 [0.98517876 0.66419662 0.10023583 ... 0.68948437 0.25024012 0.52529271]]
[[0.44808692 0.51562663 0.75742219 ... 0.6622625  0.66495454 0.17056192]
 [0.6256829  0.80584234 0.23917839 ... 0.03570832 0.25304521 0.89235821]
 [0.1567039  0.89665202 0.51963884 ... 0.84222879 0.83449943 0.13613607]
 ...
 [0.59083797 0.22760909 0.38454295 ... 0.728666   0.32268938 0.21410709]
 [0.53917332 0.86625342 0.32344217 ... 0.92230648 0.30546233 0.00376581]
 [0.86038865 0.46518974 0.99009556 ... 0.44932675 0.24932299 0.82888327]]


In [0]:
def mult(a, b):
    lst = []
    tmp = []
    x = 0.0
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(b.shape[0]):
                x += a[i][k]*b[k][j]
            tmp.append(x)
            x = 0.0
        print(tmp)
        lst.append(list(tmp))
        tmp = []
    print(lst)
  
    return lst

In [0]:
def np_mult(a, b):
    
  
    return np.dot(a,b)

In [0]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.15 ms, sys: 232 µs, total: 1.38 ms
Wall time: 12.6 ms


In [0]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

[27.687746199263373, 25.83877334095403, 25.562103813078537, 25.940677692025528, 25.368315105161766, 26.87632502019553, 28.90307316877353, 25.67467934604743, 29.30227943262602, 24.760728055325256, 24.471591385614424, 25.50302300230263, 24.444229537119774, 26.99230514817821, 26.892382717386287, 28.634547814598225, 27.91418239470474, 24.541879822727413, 27.80769152852838, 25.56741729870003, 25.618449527615915, 26.140200522136215, 28.015763593854242, 27.13500638911264, 26.576026067826312, 25.782341635315316, 25.464680909383986, 25.48397867329255, 26.19451894188461, 26.75389304826704, 26.311464832950374, 25.473880615265283, 28.325647833854397, 26.53023635203554, 28.407556646658264, 27.84467955386144, 24.96266805854938, 28.8658543885393, 26.583817442045994, 27.771197144301794, 24.623021291880683, 26.416247938571384, 28.659989341626805, 26.895342294286703, 23.996202939363272, 23.54070524570055, 22.041839977171573, 24.673407713970956, 26.59788501237663, 29.416816373763417, 26.17919034541467, 2

In [0]:
print(len(M1))

100


In [0]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.3749001936957939e-11

In [0]:
a = [[23, 32, 234], [23, 465, 56]]
print(len(a[0]))

3


### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [0]:
np.random.sample(3)

array([0.31080705, 0.26988077, 0.0393439 ])

In [0]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.92355992 0.60730273 0.08885085] [0.20841517 0.29817234 0.02864713]


In [0]:
def scalar_product(a,b):
    print(a[0]*b[0]+a[1]*b[1]+a[2]*b[2])
    return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]

In [0]:
def np_scalar_product(a,b):
    print(a.dot(b))
    return a.dot(b)

In [0]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

0.37611009343201596
CPU times: user 304 µs, sys: 52 µs, total: 356 µs
Wall time: 363 µs
0.37611009343201596
CPU times: user 313 µs, sys: 8 µs, total: 321 µs
Wall time: 946 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  result = 0
  for i in np.diag(a):
      if i % 2 == 0:
          result += i
    
  return result

In [0]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[1, 9, 6, 2, 8],
       [9, 4, 7, 5, 5],
       [9, 7, 8, 1, 3],
       [7, 3, 5, 2, 5],
       [1, 1, 7, 2, 8]])

In [0]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 53 µs, sys: 10 µs, total: 63 µs
Wall time: 66 µs


22

In [0]:
%%time
np.diag(a)[1::2].sum()

CPU times: user 72 µs, sys: 10 µs, total: 82 µs
Wall time: 87.3 µs


6

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [0]:
X = np.random.rand(3,3)
print(X)
print(np.cumsum(X,axis=1))

[[0.07731831 0.23843203 0.46715229]
 [0.69121597 0.24413223 0.29690199]
 [0.68241417 0.80482259 0.70941345]]
[[0.07731831 0.31575034 0.78290263]
 [0.69121597 0.9353482  1.23225018]
 [0.68241417 1.48723676 2.19665022]]


In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return np.cumsum(A, axis=1)



In [0]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 
print(A)

%time S2 = np_sec_av(A)

[4.69704304e-01 8.74783644e-01 7.91822323e-01 5.30060005e-01
 5.53200469e-01 5.31545392e-01 2.97589169e-01 5.83619528e-01
 4.19046287e-01 8.16882892e-02 9.51680155e-01 3.81328192e-02
 7.83253013e-01 3.16424318e-01 5.90873704e-01 8.88797369e-01
 6.61223318e-01 6.02553972e-01 2.92178548e-01 1.65749315e-01
 1.69061274e-01 2.69717875e-01 5.79265454e-01 8.86895348e-01
 2.11663069e-01 6.35904899e-01 1.98494681e-01 5.12166332e-01
 7.71967611e-01 9.58132151e-01 2.62224118e-01 7.64500041e-01
 6.32734282e-01 4.36576477e-02 6.34784974e-01 5.41321321e-01
 9.84759309e-01 4.59389652e-01 4.38025464e-01 3.46818447e-01
 6.01977018e-01 9.49382507e-01 9.91384542e-01 9.77170433e-01
 9.34227506e-02 8.52403974e-02 7.39283612e-01 6.48013039e-02
 6.86515510e-01 8.60922989e-01 2.85123714e-01 7.04324455e-01
 7.20449557e-01 2.29200812e-01 7.40292874e-01 7.71665401e-01
 8.73043251e-01 1.00431992e-02 4.74372930e-01 5.67544464e-01
 6.60952449e-01 4.65705248e-01 5.92675030e-01 8.90379622e-01
 2.37086198e-01 1.897633

AxisError: ignored

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    arr = np.array([a[0]])
    num = np.array([])
    x = a[0]
    count = 0
    for i in a:
      if i == x:
        count += 1
      else:
        num = np.append(num, count)
        count = 1
        x = i
        arr = np.append(arr, x)
    num = np.append(num, count)
    print(arr,num)
    return arr, num

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

[1 2 3 1 5 2 3] [1. 2. 2. 2. 2. 1. 2.]
CPU times: user 2.2 ms, sys: 0 ns, total: 2.2 ms
Wall time: 2.59 ms


### Задание 6

Задан двумерный массив $X$. Для каждой строчки массива $X$ необходимо сделать следующее преобразование.

Пусть дана строчка $x$. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (значение по умолчанию $a$=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив $x$ с преобразованным $x$ и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива $X$. Массив $X$ при этом должен остаться без изменений.


Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [0]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    Y = np.copy(X)
    Y[::2] = a
    Y[1::2] = Y[1::2] ** 3
    Y = Y[::-1]
    Y = np.concatenate((X,Y))
    return Y

In [0]:
X = np.array([i for i in range(1, 10, 2)])
print(X)
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)
print(S2)

[1 3 5 7 9]
CPU times: user 68 µs, sys: 8 µs, total: 76 µs
Wall time: 81.3 µs
[  1   3   5   7   9   5 343   5  27   5]


In [0]:
m1[0,2]

0.020869580686151745

In [0]:
m1 = np.asarray(np.random.rand(3,4))
print(m1)
m2 = np.asarray(np.random.rand(4,3))
print(m2)
mm = m1 @ m2

print('----------- m1 @ m2 -----------')
print(mm)

def no_numpy_mult(first, second):
    
    first_rows,first_cols = len(first),len(first[0])
    sec_rows,sec_cols = len(second),len(second[0])

    assert first_cols == sec_rows
    
    result = []

    for r in range(first_rows):
        res_line = []
        for c in range(sec_cols):
            res = 0
            for i in range(first_cols):
                res += first[r][i] * second[i][c]
            res_line.append(res)
        result.append(res_line)
    return result

print('------------ no_numpy_mult --------------')

print(no_numpy_mult(m1,m2))

print('------------ numpy_mult --------------')


def numpy_mult(first, second):
    
    return first @ second

print(numpy_mult(m1,m2))

[[0.06270309 0.07612296 0.52463233 0.14951178]
 [0.25874909 0.87242854 0.96267292 0.0704089 ]
 [0.32782856 0.3665749  0.52746285 0.99255385]]
[[0.70131745 0.34216487 0.96214391]
 [0.76591695 0.40174401 0.37732026]
 [0.29379695 0.17385597 0.6146846 ]
 [0.26895129 0.46634587 0.30534084]]
----------- m1 @ m2 -----------
[[0.2966254  0.2129714  0.4571876 ]
 [1.15143998 0.63922913 1.19137776]
 [0.93259343 0.81401665 1.08102491]]
------------ no_numpy_mult --------------
[[0.2966254011535842, 0.21297140165054848, 0.45718760062755065], [1.1514399840658804, 0.6392291266954258, 1.1913777554838016], [0.9325934323481755, 0.8140166467550145, 1.0810249060652648]]
------------ numpy_mult --------------
[[0.2966254  0.2129714  0.4571876 ]
 [1.15143998 0.63922913 1.19137776]
 [0.93259343 0.81401665 1.08102491]]


In [12]:
def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """

    #YOUR CODE
    
    Y = np.copy(X)
    
    for n in range(Y.shape[0]):
        Y[n,1::2] = a
        Y[n,0::2] = Y[n,0::2] ** 3
    
    Y = Y[:,::-1]
        
    return np.concatenate((np.copy(X),Y),axis=1)

transform(np.array([[1,2,3,4,5],[1,2,3,4,5]],dtype=float),-1)

array([[  1.,   2.,   3.,   4.,   5., 125.,  -1.,  27.,  -1.,   1.],
       [  1.,   2.,   3.,   4.,   5., 125.,  -1.,  27.,  -1.,   1.]])